Algoritmo "VOLUME"

Var
   VOLUME, ALTURA, R: REAL

Inicio
      ESCREVAL("CALCULO DE VOLUME: ")
      ESCREVAL("                 ")
      ESCREVA("DIGITE A ALTURA DO RECIPIENTE: ")
      LEIA(ALTURA)
      ESCREVAL("                 ")
      ESCREVA("DIGITE O RAIO DO RECIPIENTE: ")
      LEIA(R)

             VOLUME:=(3.14159*(R*R)*ALTURA)

             ESCREVA("O VOLUME DO RECIPIENTE É: ", VOLUME)


Fimalgoritmo